export { default as BrowseCourse } from './BrowserCourse'
export { default as MyCourse } from './MyCourse'
export { default as Lectures } from './Lectures'
export { default as Blank } from './Blank'
export { default as Assignment } from './Assignment'
export { default as Certificate } from './Certificate'
export { default as Exam } from './Exam'
