export { default as SignupOTP } from './SignupOTP'
export { default as SignUp } from './SignUp'
export { default as BasicInfo } from './BasicInfo'
export { default as SignUpSuccess } from './SignUpSuccess'
export { default as SignUpInfo } from './SignUpInfo'