export { default as CourseCard } from './CourseCard'
export { default as CountCard } from './CountCard'
export { default as CourseDetailCard } from './CourseDetailCard'
export {default as CreateExam } from './CreateExam'
export { default as CreateSection } from './CreateSection'
export { default as CreateQuestion} from './CreateQuestion'
export {default as Completed} from './Completed'
export {default as Createquestion1} from './Createquestion1'
export {default as CreateDashboard} from './CreateDashboard'
export {default as Createquestion2} from './Createquestion2'
export {default as CreateAssignment} from './CreateAssignment'
export {default as ReviewAssignment} from './ReviewAssignment'
export {default as GradingAssignment} from './GradingAssignment'
export {default as AssignmentSummary} from './AssignmentSummary'
export {default as ReviewSummary} from './ReviewSummary'
export {default as GradingSummary} from './GradingSummary'
// export {default as CertificateDashboard} from './CertificateDashboard'
// export {default as CertificateInstitutioninfo} from './CertificateInstitutionInfo'
// export {default as CertificateStudentInfo} from './CertificateStudentInfo'
// export {default as CertificateStyle} from '../Courses/CertificateStyle'
// export {default as CertificateCreate} from './CertificateCreate'
// export {default as CertificateVerify} from './CertificateVerify'
