export { default as CourseCard } from './CourseCard'
export { default as CountCard } from './CountCard'
export { default as CourseDetailCard } from './CourseDetailCard'
export {default as CreateExam } from './CreateExam'
export { default as CreateSection } from './CreateSection'
export { default as CreateQuestion} from './CreateQuestion'
export {default as Completed} from './Completed'
export {default as Createquestion1} from './Createquestion1'
export {default as CreateDashboard} from './CreateDashboard'
export {default as Createquestion2} from './Createquestion2'